#!/usr/bin/env python3
"""
PhD Literature Extraction Pipeline — Gap Taxonomy
===================================================
Classifies research gaps into tiers: Core, Supporting, Niche.

Core gaps drive the dissertation and get full Opus deep analysis.
Supporting gaps provide context and get lighter Sonnet analysis.
Niche gaps are logged in GAP_TRACKER but excluded from the elimination matrix.

Usage:
    python3 gap_taxonomy.py --classify          # Classify all gaps (writes to sheet)
    python3 gap_taxonomy.py --classify-dry-run  # Preview classifications
    python3 gap_taxonomy.py --stats             # Show tier distribution
    python3 gap_taxonomy.py --override GAP_001 Core "Central to Paper 2"
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import threading
import time
from datetime import datetime
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import box

from config import (
    CLAUDE_CLI,
    CLAUDE_MODEL,
    SPREADSHEET_ID,
    SHEETS_WRITE_DELAY,
    TIER_CORE,
    TIER_SUPPORTING,
    TIER_NICHE,
    VALID_TIERS,
    GAP_CLASSIFY_TIMEOUT,
    GAP_CLASSIFY_BATCH_SIZE,
)
from populator import SheetPopulator, authenticate, retry_on_api_error

console = Console()


# ─── CLASSIFICATION PROMPT ─────────────────────────────────

CLASSIFY_SYSTEM_PROMPT = """You are classifying research gaps for a PhD dissertation: "[TITLE_PLACEHOLDER — regenerated by codegen]"

CLASSIFICATION RULES:
CORE: This gap is directly addressable by the dissertation's research design:
  - Uses the dissertation's core independent and dependent variables
  - Is methodologically feasible with available databases
  - Falls within the dissertation's theoretical framework

SUPPORTING: This gap is relevant and worth tracking but not directly testable:
  - Related variables but not the exact ones in the dissertation
  - Different methodology or data requirements
  - Provides theoretical or contextual grounding

NICHE: This gap is a hyper-specific observation unlikely to inform the research design

RULES:
- When in doubt between Core and Supporting, choose Supporting
- When in doubt between Supporting and Niche, choose Supporting

Return a JSON array: [{"gap_id": "GAP_XXX", "tier": "Core|Supporting|Niche", "justification": "1-2 sentence reason"}]
Return ONLY the JSON array. No markdown, no code fences."""


# ─── GAP TAXONOMY ENGINE ──────────────────────────────────

class GapTaxonomy:
    """Classifies and manages gap tier assignments."""

    def __init__(self, sheet_id: str = ""):
        self._sheet_id = sheet_id or SPREADSHEET_ID
        self._pop = SheetPopulator(on_status=lambda msg: console.print(f"  {msg}"))

    def classify_all_gaps(self, dry_run: bool = False) -> list[dict]:
        """
        Classify all gaps from GAP_TRACKER into Core/Supporting/Niche.

        Args:
            dry_run: If True, print classifications without writing to sheet.

        Returns:
            List of dicts: [{gap_id, tier, justification}, ...]
        """
        self._pop._ensure_connected()

        # Read all gaps from GAP_TRACKER
        gaps = self._read_gaps_from_tracker()
        if not gaps:
            console.print("  [yellow]No gaps found in GAP_TRACKER[/]")
            return []

        console.print(f"  [bold]{len(gaps)} gaps to classify[/]")

        # Batch if needed
        all_classifications = []
        batches = [
            gaps[i:i + GAP_CLASSIFY_BATCH_SIZE]
            for i in range(0, len(gaps), GAP_CLASSIFY_BATCH_SIZE)
        ]

        for batch_idx, batch in enumerate(batches):
            if len(batches) > 1:
                console.print(f"\n  Batch {batch_idx + 1}/{len(batches)} ({len(batch)} gaps)")

            classifications = self._classify_batch(batch)
            if classifications:
                all_classifications.extend(classifications)
            else:
                console.print(f"  [red]Batch {batch_idx + 1} classification failed[/]")

        if not all_classifications:
            console.print("  [red]No classifications returned[/]")
            return []

        # Display results
        self._display_classifications(all_classifications)

        if not dry_run:
            applied = self.apply_classifications(all_classifications)
            console.print(f"\n  [bold green]Applied {applied} tier classifications to GAP_TRACKER[/]")

        return all_classifications

    def apply_classifications(
        self, classifications: list[dict], set_by: str = "AI"
    ) -> int:
        """
        Write tier classifications to GAP_TRACKER sheet.

        Args:
            classifications: [{gap_id, tier, justification}, ...]
            set_by: "AI" or "Manual"

        Returns:
            Number of rows updated.
        """
        self._pop._ensure_connected()

        # Build lookup
        class_map = {}
        for c in classifications:
            gid = c.get("gap_id", "")
            tier = c.get("tier", "")
            if gid and tier in VALID_TIERS:
                class_map[gid] = c

        if not class_map:
            return 0

        # Read current GAP_TRACKER to find row positions
        ws = self._pop._get_worksheet("GAP_TRACKER")
        header_map = self._pop._get_header_map("GAP_TRACKER")
        all_rows = ws.get_all_values()

        if len(all_rows) < 2:
            return 0

        # Find column indices for new taxonomy fields
        # If columns don't exist yet, we need to add headers
        tier_col = header_map.get("Tier")
        justification_col = header_map.get("Tier_Justification")
        set_by_col = header_map.get("Tier_Set_By")
        set_at_col = header_map.get("Tier_Set_At")

        if tier_col is None:
            # Need to add headers — append after last existing column
            self._add_taxonomy_headers(ws, all_rows[0])
            # Re-read headers
            header_map = self._pop._get_header_map("GAP_TRACKER")
            tier_col = header_map.get("Tier")
            justification_col = header_map.get("Tier_Justification")
            set_by_col = header_map.get("Tier_Set_By")
            set_at_col = header_map.get("Tier_Set_At")

        if tier_col is None:
            console.print("  [red]Failed to find/create Tier column[/]")
            return 0

        gid_col = header_map.get("Gap_ID", 0)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        from gspread import Cell
        cells = []
        updated = 0

        for row_idx, row in enumerate(all_rows[1:], start=2):
            if len(row) <= gid_col:
                continue
            gid = row[gid_col].strip()
            if gid not in class_map:
                continue

            c = class_map[gid]
            cells.append(Cell(row=row_idx, col=tier_col + 1, value=c["tier"]))
            if justification_col is not None:
                cells.append(Cell(
                    row=row_idx, col=justification_col + 1,
                    value=str(c.get("justification", ""))[:500]
                ))
            if set_by_col is not None:
                cells.append(Cell(row=row_idx, col=set_by_col + 1, value=set_by))
            if set_at_col is not None:
                cells.append(Cell(row=row_idx, col=set_at_col + 1, value=now))
            updated += 1

        if cells:
            ws.update_cells(cells)

        return updated

    def override_tier(
        self, gap_id: str, new_tier: str, justification: str = ""
    ) -> bool:
        """
        Manually override a gap's tier classification.

        Returns True if successful.
        """
        if new_tier not in VALID_TIERS:
            console.print(f"  [red]Invalid tier '{new_tier}'. Must be: {', '.join(VALID_TIERS)}[/]")
            return False

        classification = [{
            "gap_id": gap_id,
            "tier": new_tier,
            "justification": justification or f"Manual override to {new_tier}",
        }]

        applied = self.apply_classifications(classification, set_by="Manual")
        if applied > 0:
            console.print(f"  [green]{gap_id} → {new_tier}[/]")
            return True
        else:
            console.print(f"  [red]Gap {gap_id} not found in GAP_TRACKER[/]")
            return False

    def get_gaps_by_tier(self, tier: str) -> list[dict]:
        """Return all gaps with a specific tier."""
        if tier not in VALID_TIERS:
            return []
        self._pop._ensure_connected()
        gaps = self._read_gaps_from_tracker()
        return [g for g in gaps if g.get("tier", "") == tier]

    def get_tier_stats(self) -> dict:
        """Return tier distribution counts."""
        self._pop._ensure_connected()
        gaps = self._read_gaps_from_tracker()
        stats = {TIER_CORE: 0, TIER_SUPPORTING: 0, TIER_NICHE: 0, "Unclassified": 0}
        for g in gaps:
            tier = g.get("tier", "")
            if tier in VALID_TIERS:
                stats[tier] += 1
            else:
                stats["Unclassified"] += 1
        return stats

    def show_stats(self) -> None:
        """Display tier distribution in terminal."""
        stats = self.get_tier_stats()
        total = sum(stats.values())

        table = Table(title="Gap Tier Distribution", box=box.ROUNDED)
        table.add_column("Tier", style="bold")
        table.add_column("Count", justify="right")
        table.add_column("Pct", justify="right")
        table.add_column("In Matrix?")
        table.add_column("Analysis Model")

        style_map = {
            TIER_CORE: "blue",
            TIER_SUPPORTING: "yellow",
            TIER_NICHE: "dim",
            "Unclassified": "red",
        }

        for tier, count in stats.items():
            pct = f"{count / total * 100:.1f}%" if total > 0 else "0%"
            in_matrix = "Yes" if tier in (TIER_CORE, TIER_SUPPORTING) else "No"
            model = {
                TIER_CORE: "Opus (deep)",
                TIER_SUPPORTING: "Sonnet (lighter)",
                TIER_NICHE: "Skipped",
                "Unclassified": "Opus (default)",
            }.get(tier, "?")
            table.add_row(
                tier, str(count), pct, in_matrix, model,
                style=style_map.get(tier, "white"),
            )

        console.print(table)

    # ═══════════════════════════════════════════════════════════
    # INTERNAL METHODS
    # ═══════════════════════════════════════════════════════════

    @retry_on_api_error()
    def _read_gaps_from_tracker(self) -> list[dict]:
        """Read all gaps from GAP_TRACKER sheet."""
        ws = self._pop._get_worksheet("GAP_TRACKER")
        rows = ws.get_all_records()
        gaps = []
        for row in rows:
            gap_id = str(row.get("Gap_ID", "")).strip()
            if not gap_id:
                continue
            gaps.append({
                "gap_id": gap_id,
                "gap_type": str(row.get("Gap_Type", "")),
                "gap_statement": str(row.get("Gap_Statement", "")),
                "severity": str(row.get("Severity", "")),
                "paper_assignment": str(row.get("Paper_Assignment", "")),
                "variables_needed": str(row.get("Variables_Needed", "")),
                "methodology_needed": str(row.get("Methodology_Needed", "")),
                "tier": str(row.get("Tier", "")),
            })
        return gaps

    def _classify_batch(self, gaps: list[dict]) -> list[dict]:
        """Send a batch of gaps to Claude for classification."""
        gap_text = "\n".join(
            f'{g["gap_id"]} [{g["gap_type"]}] (Assignment: {g["paper_assignment"]}): '
            f'"{g["gap_statement"][:200]}"'
            for g in gaps
        )

        user_prompt = (
            f"Classify the following {len(gaps)} research gaps:\n\n"
            f"{gap_text}\n\n"
            f"Return a JSON array with one object per gap: "
            f'[{{"gap_id": "GAP_XXX", "tier": "Core|Supporting|Niche", "justification": "..."}}]'
        )

        stdout = self._run_claude(
            prompt=user_prompt,
            system=CLASSIFY_SYSTEM_PROMPT,
            model=CLAUDE_MODEL,
            timeout=GAP_CLASSIFY_TIMEOUT,
            label=f"Classifying {len(gaps)} gaps",
        )

        if not stdout:
            return []

        parsed = self._parse_json_output(stdout)
        if not parsed or not isinstance(parsed, list):
            return []

        # Validate each classification
        valid = []
        for item in parsed:
            if not isinstance(item, dict):
                continue
            gid = item.get("gap_id", "")
            tier = item.get("tier", "")
            if gid and tier in VALID_TIERS:
                valid.append({
                    "gap_id": gid,
                    "tier": tier,
                    "justification": str(item.get("justification", ""))[:500],
                })

        return valid

    def _add_taxonomy_headers(self, ws, current_headers: list[str]) -> None:
        """Add Tier, Tier_Justification, Tier_Set_By, Tier_Set_At headers."""
        new_headers = ["Tier", "Tier_Justification", "Tier_Set_By", "Tier_Set_At"]
        existing = set(h.strip() for h in current_headers if h.strip())
        to_add = [h for h in new_headers if h not in existing]

        if not to_add:
            return

        start_col = len(current_headers) + 1
        from gspread import Cell
        cells = [
            Cell(row=1, col=start_col + i, value=h)
            for i, h in enumerate(to_add)
        ]
        ws.update_cells(cells)
        console.print(f"  [dim]Added {len(to_add)} taxonomy headers to GAP_TRACKER[/]")
        time.sleep(SHEETS_WRITE_DELAY)

        # Invalidate cached header map
        self._pop.invalidate_next_row("GAP_TRACKER")

    def _display_classifications(self, classifications: list[dict]) -> None:
        """Display classification results in a Rich table."""
        table = Table(title="Gap Classifications", box=box.SIMPLE)
        table.add_column("Gap ID", style="bold")
        table.add_column("Tier")
        table.add_column("Justification", max_width=80)

        style_map = {TIER_CORE: "blue", TIER_SUPPORTING: "yellow", TIER_NICHE: "dim"}

        # Sort: Core first, then Supporting, then Niche
        tier_order = {TIER_CORE: 0, TIER_SUPPORTING: 1, TIER_NICHE: 2}
        sorted_c = sorted(classifications, key=lambda c: tier_order.get(c.get("tier", ""), 3))

        for c in sorted_c:
            tier = c.get("tier", "?")
            table.add_row(
                c.get("gap_id", "?"),
                tier,
                c.get("justification", ""),
                style=style_map.get(tier, "white"),
            )

        console.print(table)

        # Summary
        counts = {}
        for c in classifications:
            t = c.get("tier", "Unknown")
            counts[t] = counts.get(t, 0) + 1

        console.print(f"\n  Summary: {counts}")

    # ═══════════════════════════════════════════════════════════
    # CLAUDE CLI (reused pattern from gap_matrix_analyzer.py)
    # ═══════════════════════════════════════════════════════════

    def _run_claude(
        self, prompt: str, system: str, model: str, timeout: int, label: str = "Claude"
    ) -> str | None:
        """Spawn Claude CLI subprocess. Returns raw stdout or None."""
        cmd = [
            CLAUDE_CLI,
            "-p", prompt,
            "--output-format", "json",
            "--model", model,
            "--max-turns", "1",
            "--no-session-persistence",
            "--append-system-prompt", system,
        ]

        try:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold blue]{task.description}"),
                console=console,
            ) as progress:
                progress.add_task(label)

                process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                    env={**os.environ, "CLAUDE_CODE_HEADLESS": "1"},
                )

                stdout_lines = []
                stderr_lines = []

                def read_stream(stream, line_list):
                    for line in stream:
                        line_list.append(line)

                stdout_thread = threading.Thread(
                    target=read_stream, args=(process.stdout, stdout_lines), daemon=True
                )
                stderr_thread = threading.Thread(
                    target=read_stream, args=(process.stderr, stderr_lines), daemon=True
                )
                stdout_thread.start()
                stderr_thread.start()

                try:
                    process.wait(timeout=timeout)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
                    console.print(f"  [red]TIMEOUT after {timeout}s[/]")
                    return None

                stdout_thread.join(timeout=5)
                stderr_thread.join(timeout=5)

            stdout_full = "".join(stdout_lines)
            stderr_full = "".join(stderr_lines)

            if process.returncode != 0:
                console.print(f"  [red]Claude exited with code {process.returncode}[/]")
                if stderr_full.strip():
                    console.print(f"  [dim]stderr: {stderr_full[:300]}[/]")
                return None

            return stdout_full

        except FileNotFoundError:
            console.print("  [red]'claude' CLI not found[/]")
            return None
        except Exception as e:
            console.print(f"  [red]Unexpected error: {e}[/]")
            return None

    def _parse_json_output(self, stdout: str) -> list[dict] | None:
        """Parse Claude CLI JSON output (handles envelope format)."""
        stdout = stdout.strip()
        if not stdout:
            return None

        try:
            envelope = json.loads(stdout)
        except json.JSONDecodeError:
            return self._extract_json_array(stdout)

        if isinstance(envelope, list):
            return envelope

        if isinstance(envelope, dict) and "result" in envelope:
            result = envelope["result"]
            if isinstance(result, list):
                return result
            if isinstance(result, str):
                try:
                    parsed = json.loads(result)
                    if isinstance(parsed, list):
                        return parsed
                except json.JSONDecodeError:
                    return self._extract_json_array(result)

        return None

    def _extract_json_array(self, text: str) -> list[dict] | None:
        """Extract outermost [...] from text."""
        start = text.find("[")
        if start == -1:
            return None

        depth = 0
        in_string = False
        escape = False

        for i, ch in enumerate(text[start:], start):
            if escape:
                escape = False
                continue
            if ch == "\\":
                escape = True
                continue
            if ch == '"':
                in_string = not in_string
                continue
            if in_string:
                continue
            if ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    try:
                        result = json.loads(text[start:i + 1])
                        if isinstance(result, list):
                            return result
                    except json.JSONDecodeError:
                        return None
        return None


# ─── STANDALONE CLI ─────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Gap Taxonomy — classify gaps into Core/Supporting/Niche")
    parser.add_argument("--classify", action="store_true", help="Classify all gaps (writes to sheet)")
    parser.add_argument("--classify-dry-run", action="store_true", help="Preview classifications without writing")
    parser.add_argument("--stats", action="store_true", help="Show tier distribution")
    parser.add_argument("--override", nargs=3, metavar=("GAP_ID", "TIER", "JUSTIFICATION"),
                        help="Manually override a gap's tier")
    args = parser.parse_args()

    taxonomy = GapTaxonomy()

    console.print("\n  [bold]Gap Taxonomy Engine[/]")
    console.print("  " + "-" * 50)

    if args.stats:
        taxonomy.show_stats()
        return

    if args.override:
        gap_id, tier, justification = args.override
        taxonomy.override_tier(gap_id, tier, justification)
        return

    if args.classify or args.classify_dry_run:
        taxonomy.classify_all_gaps(dry_run=args.classify_dry_run)
        return

    # Default: show stats
    taxonomy.show_stats()


if __name__ == "__main__":
    main()
