"""
PhD Literature Discovery Pipeline — Abstract-Based Relevance Screener
=======================================================================
Uses Claude Sonnet (cheap, fast) to filter irrelevant papers by title+abstract
BEFORE expensive PDF download and Opus extraction.

Follows the same Claude CLI subprocess pattern as gap_query_builder.py.
"""
from __future__ import annotations

import json
import os
import subprocess
import threading
import time
from typing import Optional

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

from discovery_config import (
    RELEVANCE_SCREEN_THRESHOLD,
    RELEVANCE_SCREEN_BATCH_SIZE,
    RELEVANCE_SCREEN_TIMEOUT,
    CLAUDE_SONNET_MODEL,
)
from config import CLAUDE_CLI

console = Console()


# ─── SYSTEM PROMPT ──────────────────────────────────────────

SCREENING_SYSTEM_PROMPT = """You are a research relevance screener for a PhD dissertation.

PhD context: "[TITLE_PLACEHOLDER — regenerated by codegen]"

Scoring rubric (0.0-1.0):
- 0.9-1.0: Directly about the core research variables and outcomes
- 0.7-0.8: About the primary research domain with related but different variables
- 0.5-0.6: Broadly related to the research domain
- 0.3-0.4: Tangentially related
- 0.1-0.2: Minimally related — peripheral topic
- 0.0: Completely unrelated

Guidelines:
1. Score based on alignment with the configured research context
2. Consider methodology, variables, and theoretical framework overlap
3. Papers from relevant journals are more likely relevant
4. Err on the side of inclusion for borderline cases
5. If no abstract is provided, score based on title alone (with lower confidence)

Return ONLY a valid JSON array. No markdown, no code fences.

Format:
[
  {
    "index": 0,
    "score": 0.85,
    "reasoning": "Brief one-sentence explanation"
  }
]"""


# ─── SCREENING FUNCTIONS ───────────────────────────────────

def screen_paper(paper: dict, threshold: float = RELEVANCE_SCREEN_THRESHOLD) -> tuple[bool, float, str]:
    """
    Screen a single paper for relevance.

    Args:
        paper: Normalized paper dict (needs 'title', optionally 'abstract')
        threshold: Score threshold for relevance (default from config)

    Returns:
        (is_relevant, score, reasoning)
    """
    results = _run_screening_batch([paper])
    if results and len(results) > 0:
        r = results[0]
        score = r.get("score", 0.5)
        reasoning = r.get("reasoning", "No reasoning provided")
        return score >= threshold, score, reasoning

    # Fallback: pass through if screening fails
    return True, 0.5, "Screening unavailable — passed through"


def screen_batch(
    papers: list[dict],
    threshold: float = RELEVANCE_SCREEN_THRESHOLD,
) -> tuple[list[dict], list[dict]]:
    """
    Screen a batch of papers for relevance.

    Args:
        papers: List of normalized paper dicts
        threshold: Score threshold

    Returns:
        (relevant_papers, filtered_papers)
        Filtered papers have '_relevance_score' and '_relevance_reason' added.
    """
    if not papers:
        return [], []

    # Process in batches
    all_scores: list[dict] = []
    for i in range(0, len(papers), RELEVANCE_SCREEN_BATCH_SIZE):
        batch = papers[i:i + RELEVANCE_SCREEN_BATCH_SIZE]
        batch_results = _run_screening_batch(batch)

        if batch_results and len(batch_results) == len(batch):
            all_scores.extend(batch_results)
        else:
            # Fallback: pass through if screening fails for this batch
            for _ in batch:
                all_scores.append({"score": 0.5, "reasoning": "Screening failed — passed through"})

    relevant = []
    filtered = []

    for paper, score_info in zip(papers, all_scores):
        score = score_info.get("score", 0.5)
        reasoning = score_info.get("reasoning", "")
        paper["_relevance_score"] = score
        paper["_relevance_reason"] = reasoning

        if score >= threshold:
            relevant.append(paper)
        else:
            filtered.append(paper)

    return relevant, filtered


# ─── CLAUDE CLI SUBPROCESS ──────────────────────────────────

def _run_screening_batch(papers: list[dict]) -> list[dict] | None:
    """Run Claude Sonnet to score relevance of a batch of papers."""
    # Build paper descriptions
    paper_texts = []
    for i, p in enumerate(papers):
        title = p.get("title", "Untitled")
        abstract = p.get("abstract", "")
        authors = p.get("Authors", "")
        year = p.get("Year", "")
        journal = p.get("Journal", "")

        text = f"[{i}] Title: {title}"
        if authors:
            text += f"\n    Authors: {authors[:100]}"
        if year:
            text += f"\n    Year: {year}"
        if journal:
            text += f"\n    Journal: {journal}"
        if abstract:
            text += f"\n    Abstract: {abstract[:500]}"
        else:
            text += "\n    Abstract: (not available)"
        paper_texts.append(text)

    user_prompt = (
        f"Score the relevance of these {len(papers)} papers to the PhD dissertation.\n\n"
        f"PAPERS:\n" + "\n\n".join(paper_texts) + "\n\n"
        f"Return a JSON array with {len(papers)} objects, one per paper."
    )

    cmd = [
        CLAUDE_CLI,
        "-p", user_prompt,
        "--output-format", "json",
        "--model", CLAUDE_SONNET_MODEL,
        "--max-turns", "1",
        "--no-session-persistence",
        "--append-system-prompt", SCREENING_SYSTEM_PROMPT,
    ]

    try:
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            env={**os.environ, "CLAUDE_CODE_HEADLESS": "1"},
        )

        stdout_lines = []
        stderr_lines = []

        def read_stream(stream, line_list):
            for line in stream:
                line_list.append(line)

        stdout_thread = threading.Thread(
            target=read_stream, args=(process.stdout, stdout_lines), daemon=True
        )
        stderr_thread = threading.Thread(
            target=read_stream, args=(process.stderr, stderr_lines), daemon=True
        )
        stdout_thread.start()
        stderr_thread.start()

        try:
            process.wait(timeout=RELEVANCE_SCREEN_TIMEOUT)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=5)
            console.print(f"  [red]Screening TIMEOUT after {RELEVANCE_SCREEN_TIMEOUT}s[/red]")
            return None

        stdout_thread.join(timeout=5)
        stderr_thread.join(timeout=5)

        stdout_full = "".join(stdout_lines)

        if process.returncode != 0:
            return None

        return _parse_screening_output(stdout_full, len(papers))

    except FileNotFoundError:
        console.print("  [red]'claude' CLI not found[/red]")
        return None
    except Exception as e:
        console.print(f"  [red]Screening error: {e}[/red]")
        return None


def _parse_screening_output(stdout: str, expected_count: int) -> list[dict] | None:
    """Parse Claude CLI JSON output for screening scores."""
    stdout = stdout.strip()
    if not stdout:
        return None

    try:
        envelope = json.loads(stdout)
    except json.JSONDecodeError:
        return _extract_json_array(stdout)

    if isinstance(envelope, list):
        return envelope

    # Handle Claude CLI envelope
    if isinstance(envelope, dict) and "result" in envelope:
        result = envelope["result"]
        if isinstance(result, list):
            return result
        if isinstance(result, str):
            try:
                parsed = json.loads(result)
                if isinstance(parsed, list):
                    return parsed
            except json.JSONDecodeError:
                return _extract_json_array(result)

    return None


def _extract_json_array(text: str) -> list[dict] | None:
    """Extract outermost [...] from text using bracket-depth matching."""
    start = text.find("[")
    if start == -1:
        return None

    depth = 0
    in_string = False
    escape = False

    for i, ch in enumerate(text[start:], start):
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
            if depth == 0:
                try:
                    result = json.loads(text[start:i + 1])
                    if isinstance(result, list):
                        return result
                except json.JSONDecodeError:
                    return None
    return None


# ─── STANDALONE ENTRY ────────────────────────────────────────

if __name__ == "__main__":
    # Quick self-test
    test_papers = [
        {
            "title": "Sample Relevant Paper Title for Your Research Domain",
            "abstract": "This study examines a core research question directly related to the configured research context with relevant variables and methodology.",
            "Authors": "Author, A.; Coauthor, B.",
            "Year": "2023",
            "Journal": "Top Field Journal",
        },
        {
            "title": "Completely Unrelated Paper from Different Field",
            "abstract": "This paper describes a methodology from a completely different scientific domain with no overlap to the configured research topic.",
            "Authors": "Other, C.; Researcher, D.",
            "Year": "2020",
            "Journal": "Unrelated Field Journal",
        },
        {
            "title": "Tangentially Related Paper with Partial Overlap",
            "abstract": "We investigate a topic that shares some theoretical or methodological overlap with the research domain but examines different variables and outcomes.",
            "Authors": "Related, E.; Scholar, F.",
            "Year": "2021",
            "Journal": "Broad Discipline Journal",
        },
    ]

    console.print("[bold blue]Screening 3 test papers...[/]\n")
    relevant, filtered = screen_batch(test_papers)
    console.print(f"\n[green]Relevant: {len(relevant)}[/]")
    for p in relevant:
        console.print(f"  ✅ [{p['_relevance_score']:.2f}] {p['title'][:60]}")
        console.print(f"     {p['_relevance_reason']}")
    console.print(f"\n[yellow]Filtered: {len(filtered)}[/]")
    for p in filtered:
        console.print(f"  ❌ [{p['_relevance_score']:.2f}] {p['title'][:60]}")
        console.print(f"     {p['_relevance_reason']}")
